version: '3.8'

services:
  protekauto-cms:
    build:
      context: .
      dockerfile: Dockerfile  # Используем упрощенный вариант для обхода rate limits
      args:
        - BEELINE_SMS_USER=${BEELINE_SMS_USER}
        - BEELINE_SMS_PASS=${BEELINE_SMS_PASS}
        - BEELINE_SMS_SENDER=${BEELINE_SMS_SENDER}
        - DATABASE_URL=${DATABASE_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    environment:
      # База данных (внешняя)
      - DATABASE_URL=${DATABASE_URL}
      
      # NextAuth и JWT
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      
      # AWS S3 для файлов
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      
      # URL для доступа к админке
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      
      # SMS API Билайн
      - BEELINE_SMS_USER=${BEELINE_SMS_USER}
      - BEELINE_SMS_PASS=${BEELINE_SMS_PASS}
      - BEELINE_SMS_SENDER=${BEELINE_SMS_SENDER}

      # Laximo API
      - LAXIMO_LOGIN=${LAXIMO_LOGIN}
      - LAXIMO_PASSWORD=${LAXIMO_PASSWORD}
      
      # Окружение
      - NODE_ENV=production
      
    restart: unless-stopped
    

